### ISSUE TITLE
Logo/Main Menu is missing

### ISSUE THREAD

**Issue by vincentweisser** [VitaDAO/VitaDAO-web3#11] opened 2021-07-01 12:39 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by audieleon** [comment] 2021-07-02 07:58
@vincentweisser Could you add more information here?

**Comment by audieleon** [comment] 2021-07-02 08:57
Is this a possible duplicate of #19

**Closed** 2021-07-03 11:12 UTC
Labels: bug, needs more info
